# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = 'centos/7.8'
  
  config.vm.provider "virtualbox" do |vbx|
    vbx.linked_clone = true
    vbx.customize ["modifyvm", :id, '--audio', 'none']
    end

  config.vm.define "otus_efi" do |demo|
    demo.vm.host_name = 'bootdemo'
    demo.vm.network :private_network, ip: "10.0.0.42"
    demo.vm.provision "shell",
     	name: "Configure script",
     	path: "config.sh"
  end

end
