---
- name: "inetRouter provision"
  hosts: inetRouter
  become: true

  tasks:
  - name: Add route
    command: ip route add 192.168.0.0/22 via 192.168.255.2 

- name: "centralRouter provision"
  hosts: centralRouter
  become: true

  tasks:
  - name: Add office 1 route
    command: ip route add 192.168.2.0/24 via 192.168.0.3

  - name: Add office 2 route
    command: ip route add 192.168.1.0/24 via 192.168.0.4
      
...