# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
   # ansible.verbose = "vvv"
    ansible.playbook = "provision.yml"
  end

  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "router1" do |router1|
    router1.vm.network "private_network", ip: "10.0.0.1", adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r1r2"
    router1.vm.network "private_network", ip: "10.0.10.1", adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r1r3"
    router1.vm.hostname = "router1"
  end

  config.vm.define "router2" do |router2|
    router2.vm.network "private_network", ip: "10.0.0.2", adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r1r2"
    router2.vm.network "private_network", ip: "10.0.20.2", adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r2r3"
    router2.vm.hostname = "router2"
  end

  config.vm.define "router3" do |router3|
    router3.vm.network "private_network", ip: "10.0.10.2", adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r1r3"
    router3.vm.network "private_network", ip: "10.0.20.1", adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r2r3"
    router3.vm.hostname = "router3"
  end

end
