---
- hosts: all
  become: true
  gather_facts: false

  tasks:
  - name: Install some useful network packages
    yum: name={{ item }} state=latest
    with_items:
      - tcpdump
      - traceroute
      - nmap

- name: "inetRouter provision"
  hosts: inetRouter
  become: true
  gather_facts: false

  handlers:
  - name: sshd_restart
    systemd: name='sshd' state=restarted

  - name: iptables start
    systemd: name=iptables state=restarted

  - name: load iptables rules
    shell: iptables-restore < /etc/iptables/iptables.rules

  tasks:
  - name: Add route to internal hosts
    command: ip route add 192.168.0.0/28 via 192.168.255.2

  - name: Install and start iptables
    yum: name=iptables-services state=present
    notify: iptables start

  - name: SSHD add line in config
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication no'
      line: 'PasswordAuthentication yes'
    notify: sshd_restart

  - name: Copy iptables rules
    copy:
      src: iptables.rules
      dest: /etc/iptables/
    notify: load iptables rules

  - name: Enable IP forwarding
    sysctl: name=net.ipv4.conf.all.forwarding value='1' sysctl_set=yes

- name: "centralRouter provision"
  hosts: centralRouter
  become: true
  gather_facts: false

  tasks:
  - name: Delete default route
    command: ip route del default via 10.0.2.2

  - name: Add default route
    command: ip route add default via 192.168.255.1  

  - name: Copy knock.sh script
    copy: src='knock.sh' dest='/home/vagrant/' mode='755'
  
  - name: Enable IP forwarding
    sysctl: name=net.ipv4.conf.all.forwarding value='1' sysctl_set=yes

- name: "centralServer provision"
  hosts: centralServer
  become: true
  gather_facts: false

  handlers:
  - name: Nginx start
    systemd: name='nginx' state=restarted enabled=yes

  tasks:
  - name: Delete default route
    command: ip route del default via 10.0.2.2

  - name: Add default route
    command: ip route add default via 192.168.0.1

  - name: Add route to host
    command: ip route add 192.168.11.0/24 via 192.168.0.3

  - name: Install epel repo
    yum: name=epel-release state=present

  - name: Install Nginx
    yum: name=nginx state=latest
    notify: Nginx start

  - name: Copy index.html file
    copy: src='index.html' dest='/usr/share/nginx/html/'

- name: "inetRouter2 provision"
  hosts: inetRouter2
  become: true
  gather_facts: false

  tasks:
  - name: Delete default route
    command: ip route del default via 10.0.2.2

  - name: Add default route
    command: ip route add default via 192.168.0.1

  - name: Enable IP forwarding
    sysctl: name=net.ipv4.conf.all.forwarding value='1' sysctl_set=yes

  - name: Check if firewalld is started
    systemd: name=firewalld state=started

  - name: Redirect port 8080
    command: firewall-cmd --add-forward-port=port=8080:proto=tcp:toport=80:toaddr=192.168.0.2

...