---
- hosts: all
  become: true
  gather_facts: false

  tasks:
  - name: Install some useful network packages
    yum: name={{ item }} state=latest
    with_items:
      - tcpdump
      - traceroute

- name: "inetRouter provision"
  hosts: inetRouter
  become: true
  gather_facts: false

  tasks:
  - name: Create Team0 interface
    nmcli:
      type: team
      conn_name: team0
      ifname: team0
      runner: activebackup
      ip4: 192.168.255.1/30
      state: present

  - name: Add teams-slaves
    nmcli:
      type: team-slave
      conn_name: '{{ item }}'
      ifname: '{{ item }}'
      master: team0
      state: present
    with_items:
      - eth1
      - eth2
  
  - name: Enable IP forwarding
    sysctl: name=net.ipv4.conf.all.forwarding value='1' sysctl_set=yes

  - name: Set promisc mode on Team interfaces
    command: ip link set {{ item }} promisc on
    with_items:
      - eth1
      - eth2

- name: "centralRouter provision"
  hosts: centralRouter
  become: true
  gather_facts: false

  tasks:
  - name: Create Team0 interface
    nmcli:
      type: team
      conn_name: team0
      ifname: team0
      runner: activebackup
      ip4: 192.168.255.2/30
      state: present

  - name: Add teams-slaves
    nmcli:
      type: team-slave
      conn_name: '{{ item }}'
      ifname: '{{ item }}'
      master: team0
      state: present
    with_items:
      - eth1
      - eth2

  - name: Add VLAN interfaces
    nmcli:
      type: vlan
      conn_name: eth3.{{ item }}
      vlanid: '{{ item }}'
      vlandev: eth3
      state: present
    with_items:
      - 100
      - 101

  - name: Delete default route
    command: ip route del default via 10.0.2.2

  - name: Add default route
    command: ip route add default via 192.168.255.1

  - name: Set promisc mode on Team interfaces
    command: ip link set {{ item }} promisc on
    with_items:
      - eth1
      - eth2

- name: "Test hosts VLAN provision"
  hosts: testClient1 testServer1 testClient2 testServer2
  become: true
  gather_facts: false

  handlers:
  - name: Network reload
    systemd: name=network state=restarted

  tasks:
  - name: Copy VLAN configuration file
    template:
      src: ifcfg-vlan.j2
      dest: '/etc/sysconfig/network-scripts/ifcfg-{{ vlan_name }}'
    notify: Network reload

...