# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

  config.vm.provision "ansible" do |ansible|
    # ansible.verbose = "vvv"
     ansible.playbook = "provision.yml"
   end

   config.vm.define "DynamicWeb" do |vmconfig| 
    vmconfig.vm.box = 'centos/7'
    vmconfig.vm.hostname = 'DynamicWeb'
    vmconfig.vm.network "forwarded_port", guest: 8080, host: 8080
    vmconfig.vm.network "forwarded_port", guest: 8081, host: 8081
    vmconfig.vm.network "forwarded_port", guest: 8082, host: 8082
    vmconfig.vm.provider "virtualbox" do |vbx|
     vbx.memory = "1024"
     vbx.cpus = "1"
     vbx.customize ["modifyvm", :id, '--audio', 'none']
    end
   end

end