# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :master => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150'
  },
  :slave => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.151'
  }
}

Vagrant.configure("2") do |config|

  config.vm.provision "ansible" do |ansible|
     # ansible.verbose = "vvv"
     ansible.playbook = "provision.yml"
   end

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
            vb.memory = "1024"
            vb.cpus = "1"
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end
      end
  end
end
