# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    # ansible.verbose = "vvv"
     ansible.playbook = "provision.yml"
   end

  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.10.10"
    server.vm.synced_folder "./RAS", "/vagrant", type: "rsync"
    server.vm.provision "shell",
     name: "Easy-rsa configure",
     path: "shell.sh"
  end

  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.10.20"
    client.vm.synced_folder ".", "/vagrant", disabled: true
  end
end